openMetadataInitiative/openMINDS_instances

- instances/latest/terminologies/technique/opticalCoherenceTomography.jsonld
- instances/latest/terminologies/technique/opticalCoherenceTomographyAngiography.jsonld
> Add new techniques: optical coherence tomography and optical coherence tomography angiography 

- instances/latest/terminologies/productAccessibility/controlledAccess.jsonld
- instances/latest/terminologies/productAccessibility/paidAccess.jsonld
- instances/latest/terminologies/productAccessibility/retracted.jsonld
> Create new product accessibility

- instances/latest/terminologies/technique/differentialInterferenceContrastMicroscopy.jsonld
- instances/latest/terminologies/technique/superResolutionMicroscopy.jsonld
> Add new techniques: differential interference contrast microscopy, super resolution microscopy

- instances/latest/terminologies/technique/standardization.jsonld
related to #59
@tgbugs could you please check if the IDs are ok? 
@ingrre I agree with @lzehl that this one technique covers both use cases. It doesn't matter if you reformat the information in some cases, you still standardize them. You may want to open a new issue whenever a use case comes up, where you absolutely must have something in addition to "standardization".
> Add standardization technique

- instances/latest/terminologies/analysisTechnique/magnetizationTransferRatioImageProcessing.jsonld
- instances/latest/terminologies/analysisTechnique/magnetizationTransferSaturationImageProcessing.jsonld
- instances/latest/terminologies/analysisTechnique/myelinWaterFractionImageProcessing.jsonld
definitions and synonyms will follow in a later PR. these terms need to go in now so that the bids2openminds converter can be released. (one review is sufficient)
> MRI processing techniques

- instances/latest/terminologies/MRIPulseSequence/fastLowAngleShotPulseSequence.jsonld
- instances/latest/terminologies/MRIPulseSequence/fluidAttenuatedInversionRecoveryPulseSequence.jsonld
- instances/latest/terminologies/MRIPulseSequence/magnetizationTransferPulseSequence.jsonld
> adding pulse sequences

- instances/latest/terminologies/analysisTechnique/bootstrapAggregating.jsonld
- instances/latest/terminologies/technique/bootstrapAggregating.jsonld
- instances/v3.0/terminologies/analysisTechnique/bootstrapAggregating.jsonld
- instances/v4.0/terminologies/analysisTechnique/bootstrapAggregating.jsonld
from https://github.com/openMetadataInitiative/openMINDS_controlledTerms/pull/217 
Only issue was the name of the technique and I think "bootstrap aggregating" sounds ok. This seems to be the standard and I don't feel it sounds incomplete (although I know what you mean @lzehl).
> Add new technique - Bootstrap aggregating

- instances/latest/contentTypes/text_vnd.citation-file-format
- instances/latest/contentTypes/text_vnd.citation-file-format.jsonld
- instances/v3.0/contentTypes/text_vnd.citation-file-format
- instances/v4.0/contentTypes/text_vnd.citation-file-format.jsonld
needed for BIDS datasets, among others
> Add content-type "text/vnd.citation-file-format"

- .github/workflows/openMINDS_upstream.yml
> Change "Update openMINDS_upstream" workflow to only run on push to main

- instances/latest/commonCoordinateSpaces/MNI-Colin27.jsonld
- instances/v3.0/commonCoordinateSpaces/MNI-Colin27.jsonld
- instances/v4.0/commonCoordinateSpaces/MNI-Colin27.jsonld
Shoudl be MNI-Colin27_<<version>> instead of MNIColin27_<<version>>
> MNI-Colin27 typo in 'hasVersions'

- instances/latest/parcellationEntities/JBA/JBA_frontalCingulateGyrus.jsonld
- instances/v3.0/parcellationEntities/JBA/JBA_frontalCingulateGyrus.jsonld
- instances/v4.0/parcellationEntities/JBA/JBA_frontalCingulateGyrus.jsonld
or any other references to the name of the region. Name seems to be missing 'gyrus'.
> Name for JBA_frintalCingulateGryus does not match the file name

- instances/latest/terminologies/programmingLanguage/AMPL.jsonld
- instances/v4.0/terminologies/programmingLanguage/AMPL.jsonld
hopefully fixes https://github.com/openMetadataInitiative/openMINDS_documentation/issues/38
> fixing atid in progammingLanguage AMPL

- instances/latest/terminologies/stimulationTechnique/subliminalVisualStimulation.jsonld
- instances/v3.0/terminologies/stimulationTechnique/subliminalVisualStimulation.jsonld
- instances/v4.0/terminologies/stimulationTechnique/subliminalVisualStimulation.jsonld
Updates subliminalVisualStimulation.jsonld
Relates to #154 
@UlrikeS91 this will require an EBRAINS cleanup (because the typo was also in the atid)
> fixing type in StimulationTechnique

- instances/v3.0/contentTypes/application_vnd.webalign.waln.jsonld
- instances/v3.0/contentTypes/application_vnd.webwarp.wwrp.jsonld
Forgot to remove the '/' from @type in https://github.com/openMetadataInitiative/openMINDS_instances/pull/254.
> Extra '/' in @type

- instances/latest/terminologies/MRIWeighting/PDWeighting.jsonld
- instances/latest/terminologies/MRIWeighting/R2-starWeighting.jsonld
- instances/latest/terminologies/MRIWeighting/R2Weighting.jsonld
- instances/latest/terminologies/MRIWeighting/T1RhoWeighting.jsonld
- instances/latest/terminologies/MRIWeighting/T1Weighting.jsonld
- instances/latest/terminologies/MRIWeighting/T2-starWeighting.jsonld
- instances/latest/terminologies/MRIWeighting/T2Weighting.jsonld
> Corrected at_ids of all MRIWeighting terms (bug fix)  

- .github/workflows/instance_validator.yml
Use of pipeline located in openMINDS_actions for https://github.com/openMetadataInitiative/openMINDS_instances/issues/250
> Reusable validation workflow from openMINDS_actions.

- instances/v3.0/contentTypes/application_gzip.jsonld
- instances/v3.0/terminologies/service/Neurosift.jsonld
- instances/v4.0/contentTypes/application_gzip.jsonld
- instances/v4.0/terminologies/service/Neurosift.jsonld
- gzip v3
- gzip v4
- neuroswift v3
- neuroswift v4
> fixing missing instance populations

- instances/latest/terminologies/softwareFeature/applicationProgrammingInterface.jsonld
- instances/latest/terminologies/softwareFeature/commandLineInterface.jsonld
- instances/latest/terminologies/softwareFeature/graphicalUserInterface.jsonld
- added application programming interface
- updated command line interface (ID should be updated too but this would cause right now a too big of a cleanup in EBRAINS which I would postpone for now)
- updated graphical user interface
@apdavison feel free to further adapt/optimize
> update for software interfaces

- instances/latest/terminologies/experimentalApproach/biophysics.jsonld
- instances/latest/terminologies/experimentalApproach/genetics.jsonld
- instances/latest/terminologies/experimentalApproach/pathology.jsonld
- instances/latest/terminologies/experimentalApproach/pharmacology.jsonld
see https://github.com/openMetadataInitiative/openMINDS_instances/issues/108
- I added 'pathology' (synonym: pathological approach) as new exp. approach --> @tgbugs 
- I updated 3 existing approaches to align their definitions with the others --> @lzehl
> New exp. approach and alignment of all their definitions

- .github/workflows/autopopulation.yml
The following code should solve the issue related to the creation of new folders during autopopulation.
> Fix openMINDS_actions/issues/20 - autopopulation folders generation

- instances/latest/contentTypes/application_vnd.locare+json.jsonld
related to #8
@ingrre and @blixilla, please feel free to review the content as well
> Add LocareJSON ContentType

- instances/latest/licenses/youtube.jsonld
add Standard YouTube License to license library
solves #342
> add Standard YouTube License to license library

- instances/latest/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_linear-2001-sym.jsonld
- instances/latest/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_nonlinear-2009a-asym.jsonld
- instances/latest/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_nonlinear-2009a-sym.jsonld
- instances/v3.0/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_linear-2001-sym.jsonld
- instances/v3.0/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_nonlinear-2009a-asym.jsonld
- instances/v3.0/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_nonlinear-2009a-sym.jsonld
- instances/v4.0/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_linear-2001-sym.jsonld
- instances/v4.0/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_nonlinear-2009a-asym.jsonld
- instances/v4.0/commonCoordinateSpaceVersions/MNI-ICBM152/MNI-ICBM152_nonlinear-2009a-sym.jsonld
> In CommonCoordinateSpaceVersion, "homepage" should be an IRI string, not a WebResource
